---
timesync_ntp_servers:
  - hostname: 0.rhel.pool.ntp.org
    iburst: true
  - hostname: 1.rhel.pool.ntp.org
    iburst: true
  - hostname: 2.rhel.pool.ntp.org
    iburst: true
  - hostname: 3.rhel.pool.ntp.org
    iburst: true
cockpit_packages: default
crypto_policies_policy: "DEFAULT:NO-SHA1"
tlog_scope_sssd: all
selinux_policy: targeted
selinux_state: permissive
apache_listen_port: 8080