---
collections:
  - amazon.aws
  - ansible.controller
  - ansible.netcommon
  - ansible.network
  - ansible.posix
  - ansible.security
  - ansible.utils
  - redhat.insights
  - redhat.satellite
  - redhat.rhel_idm
  - redhat.rhel_system_roles