---
- name: Configure systems to baseline standards
  hosts: managed
  become: true
  roles:
    - redhat.rhel_system_roles.timesync
    - redhat.rhel_system_roles.cockpit
    - redhat.rhel_system_roles.crypto_policies
    - redhat.rhel_system_roles.selinux
