---
- name: Install and configure an apache webserver on RHEL
  hosts: managed
  become: true
  tasks:
  ## TODO - Install apache
    - name: 

  ## TODO - Start and enable apache
    - name: 

  ## TODO - Configure Apache using template
    - name: 

  ## TODO - Copy index.html
    - name: 

  ## TODO - Apache listen_port enabled in firewalld
    - name: 
