---
timesync_ntp_servers:
  - hostname: 0.pool.ntp.org
    iburst: true
  - hostname: 1.pool.ntp.org
    iburst: true
  - hostname: 2.pool.ntp.org
    iburst: true
  - hostname: 3.pool.ntp.org
    iburst: true
cockpit_packages: default
crypto_policies_policy: "DEFAULT:NO-SHA1"
tlog_scope_sssd: all
selinux_policy: targeted
selinux_state: enforcing
apache_listen_port: 80